### ISSUE TITLE
Verify that TravisCI will have the correct image available in docker engine 

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/ZZ-DEPRECATED_kurtosis#10]
verify that we can use command line image flags to pull images from public dockerhub, or verify that travisCI docker engine will have the image we want. somehow we gotta make the image identifier work with the travisCI setup

**Comment by mieubrisse** [comment]
Superseded by https://github.com/kurtosis-tech/kurtosis/issues/61
