### ISSUE TITLE
Provide a high level logging API so that test writers don't have to worry about fmt.Print for logging

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/ZZ-DEPRECATED_kurtosis#114]
Currently test writers have to do something like:

`fmt.Fprintln(logrus.StandardLogger().Out, setupErr)`

In order to get nice printing out of logrus because it doesn't handle new lines well. If we wrapped that functionality and provided them an api in kurtosis to do it, they wouldn't need to know to do that

**Comment by mieubrisse** [comment]
Discussed, and decided that we don't need this because:
1) everything in Kurtosis uses Logrus (by our choice) which doesn't print newlines, but we don't need a wrapper here
2) everything in Ava should be configurable by the user and is coincidence that we use Logrus
