### ISSUE TITLE
Split private helper functions in initializer/test_suite_runner.go into separate ContainerManager file

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/ZZ-DEPRECATED_kurtosis#12]
initializer/test_suite_runner.go is getting pretty long, and the private functions all have similar types of functionality, docker container management. we can improve readability and modularity by separating these out.

also the separate container manager class will be useful once we implement test_controller.go...

**Comment by mieubrisse** [comment]
I think I'm okay with this - the intention of leaving them in this file was to keep the scope as small as possible, but maybe we can make ContainerManager package-private and it'll be the same
