### ISSUE TITLE
Feature Request: Return Test Output as the tests finish

### ISSUE THREAD

**Issue by aaronbuchwald** [kurtosis-tech/ZZ-DEPRECATED_kurtosis#137]
Currently all tests report back their results at the same time when the last test has finished. It would be very useful to have the tests report back their results as they finish, so that the user has a better idea of the progress that has been made.

**Comment by aaronbuchwald** [comment]
An additional related feature that would be very helpful would be to send the logs to stdout in realtime when only running a single test.

**Comment by mieubrisse** [comment]
Yeah agreed this is really annoying/confusing; I've opened #142 to track the live-logs and will take a look at this probably next week
