### ISSUE TITLE
FeatureRequest: Initial Delay on checking if a service is ready

### ISSUE THREAD

**Issue by aaronbuchwald** [kurtosis-tech/ZZ-DEPRECATED_kurtosis#138]
Some services are expected to take a while to startup, so it would be helpful to be able to specify an initial delay before checking if a service is ready.

**Comment by mieubrisse** [comment]
Hey @aaronbuchwald , the AvailabilityChecker will actually just keep retrying and retrying until the service is up or the timeout is hit, so you should be able to meet this ask by extending the timeout in your availability checker core

**Comment by aaronbuchwald** [comment]
You're right this is unnecessary. I was basing the logic off of how the health check works in gecko, but it shouldn't make a difference. I'll close the issue
