### ISSUE TITLE
Feature Request: named services and clarity of what command each service was started with

### ISSUE THREAD

**Issue by aaronbuchwald** [kurtosis-tech/ZZ-DEPRECATED_kurtosis#140]
Currently services are known by an integer service ID (which starts at a pre-determined large number). It would be helpful if the interactions with a given service were more easily distinguishable.

For example, when the command list is logged, which specifies the command that was used to start the node, it's not abundantly clear which command list corresponds to which service and names would make them much easier to differentiate.

**Comment by mieubrisse** [comment]
This would involve swapping swapping ServiceID to be a string rather than an int; seems like a good idea to me
