### ISSUE TITLE
Make Docker Manager abstract away all docker management

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/ZZ-DEPRECATED_kurtosis#25]
Make docker-manager abstract all the docker management, only exposing user-friendly methods like StartDockerContainer(JsonRpcServiceConfig) and StopDockerContainer. That way, the client doesn't need to know about the internals of how Docker instantiates containers, the Docker config classes or host port mapping objects, etc.

Then, SvcNetworkConfig gets to be as simple as dockerManager.startContainer(svcConfig)

**Comment by mieubrisse** [comment]
Done
