### ISSUE TITLE
In ServiceNetworkConfig, make struct fields have stronger type system

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/ZZ-DEPRECATED_kurtosis#49]
Right now, there are several fields that have very broad types:

serviceConfigs map[int]int

serviceDependencies map[int]map[int]bool

But we can implement intermediate types to make this more readable. for example:

type ServiceId int

And then have serviceDependencies be  map[ServiceId]map[...]bool or something like this

**Comment by mieubrisse** [comment]
Done!
