### ISSUE TITLE
Automatic Image Pulling not Automatically Pulling Images

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/ZZ-DEPRECATED_kurtosis#61]

**Comment by mieubrisse** [comment]
Def want to fix this - in the build script we're just doing 'docker pull' until this is fixed

**Comment by mieubrisse** [comment]
Means deleting the 'docker pull' in the buildscript code and fixing any problems that arise

**Comment by galenmarchetti** [comment]
verified in ava-e2e-tests here: https://github.com/kurtosis-tech/ava-e2e-tests/pull/37
